name: Release

on:
  workflow_dispatch:

jobs:
  prepare:
    name: Prepare
    uses: ./.github/workflows/prepare.yml

  build:
    name: Build
    needs: prepare
    uses: ./.github/workflows/build.yml
    with:
      ver: ${{ needs.prepare.outputs.ver }}

  makepkg:
    name: Makepkg
    needs: makepkg
    uses: ./.github/workflows/makepkg.yml
    with:
      ver: ${{ needs.prepare.outputs.ver }}
