name: Release

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      workflow:
        description: "set workflow to download artifact"
        required: false
        type: string

permissions:
  contents: read
  packages: write
  
jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    outputs:
      workflow: ${{ steps.setup.outputs.workflow }}
      
    steps:
      - name: set workflow
        id: setup
        shell: bash
        run: |
          if [ "${{ inputs.wolkflow }}" == '' ];
          then
            echo "workflow=release.yml" >> "$GITHUB_OUTPUT"
          else
            echo "workflow=${{ inputs.wolkflow }}" >> "$GITHUB_OUTPUT"
          fi

  prepare:
    name: Prepare
    uses: ./.github/workflows/prepare.yml
    secrets: inherit

  build:
    name: Build
    needs: [setup, prepare]
    uses: ./.github/workflows/build.yml
    with:
      ver: ${{ needs.prepare.outputs.ver }}
      workflow: ${{ needs.setup.outputs.workflow }}
    secrets: inherit

  makepkg:
    name: Makepkg
    needs: [setup, prepare, build]
    uses: ./.github/workflows/makepkg.yml
    with:
      ver: ${{ needs.prepare.outputs.ver }}
      workflow: ${{ needs.setup.outputs.workflow }}
    secrets: inherit

  release:
    name: release
    needs: [setup, prepare, build, makepkg]
    runs-on: ubuntu-latest
    steps:
      - name: download artifact
        uses: dawidd6/action-download-artifact@v3
        if: inputs.workflow != ''
        with:
          workflow: ${{ inputs.workflow }}
          workflow_conclusion: in_progress
          name: linux-rpi-btf-${{ needs.prepare.outputs.ver }}
          path: 'repo'
      - name: download artifact
        uses: dawidd6/action-download-artifact@v3
        if: inputs.workflow == ''
        with:
          workflow: release.yml
          workflow_conclusion: in_progress
          name: linux-rpi-btf-${{ needs.prepare.outputs.ver }}
          path: 'repo'
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            repo/aarch64/linux-rpi-btf-${{ needs.prepare.outputs.ver }}-aarch64.pkg.tar.zst
            repo/aarch64/linux-rpi-btf-headers-${{ needs.prepare.outputs.ver }}-aarch64.pkg.tar.zst
