name: Release

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  packages: write
  
jobs:
  prepare:
    name: Prepare
    uses: ./.github/workflows/prepare.yml
    secrets: inherit

  build:
    name: Build
    needs: prepare
    uses: ./.github/workflows/build.yml
    with:
      ver: ${{ needs.prepare.outputs.ver }}
    secrets: inherit

  makepkg:
    name: Makepkg
    needs: [prepare, build]
    uses: ./.github/workflows/makepkg.yml
    with:
      ver: ${{ needs.prepare.outputs.ver }}
    secrets: inherit

  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: release
